### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jmscarlett**
Replacing PDF to correct final author name & correct corresponding author list as requested by authors (I am ICML publication chair).  Approval for the change has been given by all authors.

### CODE REVIEW

**Review by lawrennd — APPROVED** [review]
Thanks Jonathan!

**Comment by jmscarlett** [comment]
I see the new PDF at https://github.com/mlresearch/v202/blob/gh-pages/yang23p/yang23p.pdf, but the PMLR proceedings links to https://proceedings.mlr.press/v202/yang23p/yang23p.pdf for which I still see the old PDF.  It is just a matter of waiting more time for the change to be reflected?

**Comment by lawrennd** [comment]
Thanks Jonathan, apologies somehow I've accepted some changes that seem to have blocked the recompile. I've been meaning to take a look but have had some technical difficulties getting the recompile working on my machine. If you have time to spot what the last "compiled update" is that would be helpful.

**Comment by jmscarlett** [comment]
- #19 update is reflected: https://proceedings.mlr.press/v202/li23aq/li23aq.pdf (author Huizhuo appears in PDF)
- #20 also looks updated: https://proceedings.mlr.press/v202/liu23be.html and https://proceedings.mlr.press/v202/sakaue23a.html (removed LaTeX issues from titles, though the latter still has such issues in the abstract)
- #21 also updated: https://proceedings.mlr.press/v202/segovia-martin23a.html (José instead of Jose)

...so looks to me like all the changes are reflected except this one, which is #22?  Not sure if I did something wrong when replacing the PDF.

**Comment by jmscarlett** [comment]
Hi Neil, just wanted to follow up on this.  Do you agree that it looks like v21 indeed compiled correctly, meaning any compilation issue might have been introduced in this v22?

**Pull request merged**
